name: binder
channels:
  - anaconda-nb-extensions
  - damianavila82
  - conda-forge
dependencies:
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets
  - notebook
  - XlsxWriter=1.0.4
